

GET http://localhost:3071/
Content-Type: application/json

################################################################################
###### AUTH #######################################################################

###### login
POST http://localhost:3071/api/auth/login
Content-Type: application/json

{
  "email": "wagner.castro@teste.com",
  "password": "@123Alfa"
}

################################################################################
###### USER #######################################################################

###### index
GET http://localhost:3071/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmaXJzdE5hbWUiOiJXYWduZXIiLCJsYXN0TmFtZSI6IkNhc3RybyIsImVtYWlsIjoid2FnbmVyLmNhc3Ryb0B0ZXN0ZS5jb20iLCJjcmVhdGVkQXQiOiIyMDIzLTExLTAxVDExOjQ1OjQ5Ljg5M1oiLCJ1cGRhdGVkQXQiOiIyMDIzLTExLTAxVDExOjQ1OjQ5Ljg5M1oifSwiaWF0IjoxNjk4ODYyMTE1LCJleHAiOjE2OTg4NjU3MTV9.Wxe65wQwoBMyKxi-qdPR1SczN0vwaLhKlE7LdCrRV9A


###### create
POST http://localhost:3071/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmaXJzdE5hbWUiOiJXYWduZXIiLCJsYXN0TmFtZSI6IkNhc3RybyIsImVtYWlsIjoid2FnbmVyLmNhc3Ryb0B0ZXN0ZS5jb20iLCJjcmVhdGVkQXQiOiIyMDIzLTExLTAxVDExOjQ1OjQ5Ljg5M1oiLCJ1cGRhdGVkQXQiOiIyMDIzLTExLTAxVDExOjQ1OjQ5Ljg5M1oifSwiaWF0IjoxNjk4ODYyMTE1LCJleHAiOjE2OTg4NjU3MTV9.Wxe65wQwoBMyKxi-qdPR1SczN0vwaLhKlE7LdCrRV9A
Content-Type: application/json

{
  "firstName": "Wagner",
  "lastName": "Castro",
  "email": "wagner3.castro@teste.com",
  "password": "@123Alfa"
}

###### show
GET http://localhost:3071/api/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmaXJzdE5hbWUiOiJXYWduZXIiLCJsYXN0TmFtZSI6IkNhc3RybyIsImVtYWlsIjoid2FnbmVyLmNhc3Ryb0B0ZXN0ZS5jb20iLCJjcmVhdGVkQXQiOiIyMDIzLTExLTAxVDExOjQ1OjQ5Ljg5M1oiLCJ1cGRhdGVkQXQiOiIyMDIzLTExLTAxVDExOjQ1OjQ5Ljg5M1oifSwiaWF0IjoxNjk4ODYyMTE1LCJleHAiOjE2OTg4NjU3MTV9.Wxe65wQwoBMyKxi-qdPR1SczN0vwaLhKlE7LdCrRV9A


###### update
PATCH http://localhost:3071/api/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmaXJzdE5hbWUiOiJXYWduZXIiLCJsYXN0TmFtZSI6IkNhc3RybyIsImVtYWlsIjoid2FnbmVyLmNhc3Ryb0B0ZXN0ZS5jb20iLCJjcmVhdGVkQXQiOiIyMDIzLTExLTAxVDExOjQ1OjQ5Ljg5M1oiLCJ1cGRhdGVkQXQiOiIyMDIzLTExLTAxVDExOjQ1OjQ5Ljg5M1oifSwiaWF0IjoxNjk4ODYyMTE1LCJleHAiOjE2OTg4NjU3MTV9.Wxe65wQwoBMyKxi-qdPR1SczN0vwaLhKlE7LdCrRV9A
Content-Type: application/json

{
  "firstName": "Wagner",
  "lastName": "Castro"
}

### delete
DELETE  http://localhost:3071/api/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmaXJzdE5hbWUiOiJXYWduZXIiLCJsYXN0TmFtZSI6IkNhc3RybyIsImVtYWlsIjoid2FnbmVyLmNhc3Ryb0B0ZXN0ZS5jb20iLCJjcmVhdGVkQXQiOiIyMDIzLTExLTAxVDExOjQ1OjQ5Ljg5M1oiLCJ1cGRhdGVkQXQiOiIyMDIzLTExLTAxVDExOjQ1OjQ5Ljg5M1oifSwiaWF0IjoxNjk4ODYyMTE1LCJleHAiOjE2OTg4NjU3MTV9.Wxe65wQwoBMyKxi-qdPR1SczN0vwaLhKlE7LdCrRV9A


##########################################################################
###### TODO ##############################################################

###### index
GET http://localhost:3071/api/v1/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmaXJzdE5hbWUiOiJXYWduZXIiLCJsYXN0TmFtZSI6IkNhc3RybyIsImVtYWlsIjoid2FnbmVyLmNhc3Ryb0B0ZXN0ZS5jb20iLCJjcmVhdGVkQXQiOiIyMDIzLTExLTAxVDExOjQ1OjQ5Ljg5M1oiLCJ1cGRhdGVkQXQiOiIyMDIzLTExLTAxVDExOjQ1OjQ5Ljg5M1oifSwiaWF0IjoxNjk4ODYyMTE1LCJleHAiOjE2OTg4NjU3MTV9.Wxe65wQwoBMyKxi-qdPR1SczN0vwaLhKlE7LdCrRV9A
Content-Type: application/json


###### store
POST http://localhost:3071/api/v1/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmaXJzdE5hbWUiOiJXYWduZXIiLCJsYXN0TmFtZSI6IkNhc3RybyIsImVtYWlsIjoid2FnbmVyLmNhc3Ryb0B0ZXN0ZS5jb20iLCJjcmVhdGVkQXQiOiIyMDIzLTExLTAxVDExOjQ1OjQ5Ljg5M1oiLCJ1cGRhdGVkQXQiOiIyMDIzLTExLTAxVDExOjQ1OjQ5Ljg5M1oifSwiaWF0IjoxNjk4ODYyMTE1LCJleHAiOjE2OTg4NjU3MTV9.Wxe65wQwoBMyKxi-qdPR1SczN0vwaLhKlE7LdCrRV9A
Content-Type: application/json

{
  "name": "task-1",
  "description": "Lorem Ipsum is simply dummy text of the"
}

###### show
GET http://localhost:3071/api/v1/todos/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmaXJzdE5hbWUiOiJXYWduZXIiLCJsYXN0TmFtZSI6IkNhc3RybyIsImVtYWlsIjoid2FnbmVyLmNhc3Ryb0B0ZXN0ZS5jb20iLCJjcmVhdGVkQXQiOiIyMDIzLTExLTAxVDExOjQ1OjQ5Ljg5M1oiLCJ1cGRhdGVkQXQiOiIyMDIzLTExLTAxVDExOjQ1OjQ5Ljg5M1oifSwiaWF0IjoxNjk4ODYyMTE1LCJleHAiOjE2OTg4NjU3MTV9.Wxe65wQwoBMyKxi-qdPR1SczN0vwaLhKlE7LdCrRV9A
Content-Type: application/json

###### update
PATCH  http://localhost:3071/api/v1/todos/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmaXJzdE5hbWUiOiJXYWduZXIiLCJsYXN0TmFtZSI6IkNhc3RybyIsImVtYWlsIjoid2FnbmVyLmNhc3Ryb0B0ZXN0ZS5jb20iLCJjcmVhdGVkQXQiOiIyMDIzLTExLTAxVDExOjQ1OjQ5Ljg5M1oiLCJ1cGRhdGVkQXQiOiIyMDIzLTExLTAxVDExOjQ1OjQ5Ljg5M1oifSwiaWF0IjoxNjk4ODYyMTE1LCJleHAiOjE2OTg4NjU3MTV9.Wxe65wQwoBMyKxi-qdPR1SczN0vwaLhKlE7LdCrRV9A
Content-Type: application/json

{
  "name": "task-1",
  "description": "Update tas-1",
  "isDone": 1,
  "completedDate": "2023-11-01T03:47:35.802Z"
}

###### destroy
DELETE  http://localhost:3071/api/v1/todos/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmaXJzdE5hbWUiOiJXYWduZXIiLCJsYXN0TmFtZSI6IkNhc3RybyIsImVtYWlsIjoid2FnbmVyLmNhc3Ryb0B0ZXN0ZS5jb20iLCJjcmVhdGVkQXQiOiIyMDIzLTExLTAxVDExOjQ1OjQ5Ljg5M1oiLCJ1cGRhdGVkQXQiOiIyMDIzLTExLTAxVDExOjQ1OjQ5Ljg5M1oifSwiaWF0IjoxNjk4ODYyMTE1LCJleHAiOjE2OTg4NjU3MTV9.Wxe65wQwoBMyKxi-qdPR1SczN0vwaLhKlE7LdCrRV9A

