

GET http://localhost:3071/
Content-Type: application/json

################################################################################
###### AUTH #######################################################################

###### login
POST http://localhost:3071/api/auth/login
Content-Type: application/json

{
  "email": "wagner.castro@teste.com",
  "password": "@123Alfa"
}

###### me
GET http://localhost:3071/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJmaXJzdE5hbWUiOiJXYWduZXIiLCJsYXN0TmFtZSI6IkNhc3RybyIsImVtYWlsIjoid2FnbmVyLmNhc3Ryb0B0ZXN0ZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDIzLTExLTAzVDIwOjUzOjQwLjM5NVoiLCJ1cGRhdGVkQXQiOiIyMDIzLTExLTAzVDIwOjUzOjQwLjM5NVoifSwiaWF0IjoxNjk5MDM0MDI4LCJleHAiOjE2OTkwMzc2Mjh9.1uZQ9EpGv-Ew26J8BPP_Zb252vN04sZ1XMCo7GmZeM0


################################################################################
###### USER #######################################################################

###### index
GET http://localhost:3071/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJmaXJzdE5hbWUiOiJXYWduZXIiLCJsYXN0TmFtZSI6IkNhc3RybyIsImVtYWlsIjoid2FnbmVyLmNhc3Ryb0B0ZXN0ZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDIzLTExLTAzVDIwOjUzOjQwLjM5NVoiLCJ1cGRhdGVkQXQiOiIyMDIzLTExLTAzVDIwOjUzOjQwLjM5NVoifSwiaWF0IjoxNjk5MDM0MDI4LCJleHAiOjE2OTkwMzc2Mjh9.1uZQ9EpGv-Ew26J8BPP_Zb252vN04sZ1XMCo7GmZeM0


###### create
POST http://localhost:3071/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJmaXJzdE5hbWUiOiJXYWduZXIiLCJsYXN0TmFtZSI6IkNhc3RybyIsImVtYWlsIjoid2FnbmVyLmNhc3Ryb0B0ZXN0ZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDIzLTExLTAzVDIwOjUzOjQwLjM5NVoiLCJ1cGRhdGVkQXQiOiIyMDIzLTExLTAzVDIwOjUzOjQwLjM5NVoifSwiaWF0IjoxNjk5MDM0MDI4LCJleHAiOjE2OTkwMzc2Mjh9.1uZQ9EpGv-Ew26J8BPP_Zb252vN04sZ1XMCo7GmZeM0
Content-Type: application/json

{
  "firstName": "Wagner",
  "lastName": "Castro",
  "email": "wagner.castro@teste.com",
  "password": "@123Alfa",
  "role": "admin"
}

###### show
GET http://localhost:3071/api/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJmaXJzdE5hbWUiOiJXYWduZXIiLCJsYXN0TmFtZSI6IkNhc3RybyIsImVtYWlsIjoid2FnbmVyLmNhc3Ryb0B0ZXN0ZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDIzLTExLTAzVDIwOjUzOjQwLjM5NVoiLCJ1cGRhdGVkQXQiOiIyMDIzLTExLTAzVDIwOjUzOjQwLjM5NVoifSwiaWF0IjoxNjk5MDM0MDI4LCJleHAiOjE2OTkwMzc2Mjh9.1uZQ9EpGv-Ew26J8BPP_Zb252vN04sZ1XMCo7GmZeM0


###### update
PATCH http://localhost:3071/api/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJmaXJzdE5hbWUiOiJXYWduZXIiLCJsYXN0TmFtZSI6IkNhc3RybyIsImVtYWlsIjoid2FnbmVyLmNhc3Ryb0B0ZXN0ZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDIzLTExLTAzVDIwOjUzOjQwLjM5NVoiLCJ1cGRhdGVkQXQiOiIyMDIzLTExLTAzVDIwOjUzOjQwLjM5NVoifSwiaWF0IjoxNjk5MDM0MDI4LCJleHAiOjE2OTkwMzc2Mjh9.1uZQ9EpGv-Ew26J8BPP_Zb252vN04sZ1XMCo7GmZeM0
Content-Type: application/json

{
  "firstName": "Wagner",
  "lastName": "Castro"
}

### delete
DELETE  http://localhost:3071/api/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJmaXJzdE5hbWUiOiJXYWduZXIiLCJsYXN0TmFtZSI6IkNhc3RybyIsImVtYWlsIjoid2FnbmVyLmNhc3Ryb0B0ZXN0ZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDIzLTExLTAzVDIwOjUzOjQwLjM5NVoiLCJ1cGRhdGVkQXQiOiIyMDIzLTExLTAzVDIwOjUzOjQwLjM5NVoifSwiaWF0IjoxNjk5MDM0MDI4LCJleHAiOjE2OTkwMzc2Mjh9.1uZQ9EpGv-Ew26J8BPP_Zb252vN04sZ1XMCo7GmZeM0


##########################################################################
###### TODO ##############################################################

###### index
GET http://localhost:3071/api/v1/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJmaXJzdE5hbWUiOiJXYWduZXIiLCJsYXN0TmFtZSI6IkNhc3RybyIsImVtYWlsIjoid2FnbmVyLmNhc3Ryb0B0ZXN0ZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDIzLTExLTAzVDIwOjUzOjQwLjM5NVoiLCJ1cGRhdGVkQXQiOiIyMDIzLTExLTAzVDIwOjUzOjQwLjM5NVoifSwiaWF0IjoxNjk5MDM0MDI4LCJleHAiOjE2OTkwMzc2Mjh9.1uZQ9EpGv-Ew26J8BPP_Zb252vN04sZ1XMCo7GmZeM0
Content-Type: application/json


###### store
POST http://localhost:3071/api/v1/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJmaXJzdE5hbWUiOiJXYWduZXIiLCJsYXN0TmFtZSI6IkNhc3RybyIsImVtYWlsIjoid2FnbmVyLmNhc3Ryb0B0ZXN0ZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDIzLTExLTAzVDIwOjUzOjQwLjM5NVoiLCJ1cGRhdGVkQXQiOiIyMDIzLTExLTAzVDIwOjUzOjQwLjM5NVoifSwiaWF0IjoxNjk5MDM0MDI4LCJleHAiOjE2OTkwMzc2Mjh9.1uZQ9EpGv-Ew26J8BPP_Zb252vN04sZ1XMCo7GmZeM0
Content-Type: application/json

{
  "name": "task-1",
  "description": "Lorem Ipsum is simply dummy text of the"
}

###### show
GET http://localhost:3071/api/v1/todos/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJmaXJzdE5hbWUiOiJXYWduZXIiLCJsYXN0TmFtZSI6IkNhc3RybyIsImVtYWlsIjoid2FnbmVyLmNhc3Ryb0B0ZXN0ZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDIzLTExLTAzVDIwOjUzOjQwLjM5NVoiLCJ1cGRhdGVkQXQiOiIyMDIzLTExLTAzVDIwOjUzOjQwLjM5NVoifSwiaWF0IjoxNjk5MDM0MDI4LCJleHAiOjE2OTkwMzc2Mjh9.1uZQ9EpGv-Ew26J8BPP_Zb252vN04sZ1XMCo7GmZeM0
Content-Type: application/json

###### update
PATCH  http://localhost:3071/api/v1/todos/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJmaXJzdE5hbWUiOiJXYWduZXIiLCJsYXN0TmFtZSI6IkNhc3RybyIsImVtYWlsIjoid2FnbmVyLmNhc3Ryb0B0ZXN0ZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDIzLTExLTAzVDIwOjUzOjQwLjM5NVoiLCJ1cGRhdGVkQXQiOiIyMDIzLTExLTAzVDIwOjUzOjQwLjM5NVoifSwiaWF0IjoxNjk5MDM0MDI4LCJleHAiOjE2OTkwMzc2Mjh9.1uZQ9EpGv-Ew26J8BPP_Zb252vN04sZ1XMCo7GmZeM0
Content-Type: application/json

{
  "name": "task-1",
  "description": "Update tas-1",
  "isDone": 1,
  "completedDate": "2023-11-01T03:47:35.802Z"
}

###### destroy
DELETE  http://localhost:3071/api/v1/todos/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJmaXJzdE5hbWUiOiJXYWduZXIiLCJsYXN0TmFtZSI6IkNhc3RybyIsImVtYWlsIjoid2FnbmVyLmNhc3Ryb0B0ZXN0ZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDIzLTExLTAzVDIwOjUzOjQwLjM5NVoiLCJ1cGRhdGVkQXQiOiIyMDIzLTExLTAzVDIwOjUzOjQwLjM5NVoifSwiaWF0IjoxNjk5MDM0MDI4LCJleHAiOjE2OTkwMzc2Mjh9.1uZQ9EpGv-Ew26J8BPP_Zb252vN04sZ1XMCo7GmZeM0

